spring:
  datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/datajpa?autoReconnect=True
   username: root
   password: tnwls5722!

  jpa:
   hibernate:
    ddl-auto: create
   properties:
    hibernate:
 #      show_sql: true
      format_sql: true

  data:
    web:
      pageable:
        default-page-size: 10

logging.level:
    org.hibernate.SQL: debug
 #  org.hibernate.type: trace